### ISSUE TITLE
Add complete styles to the theme

### ISSUE THREAD

**Issue by aravindballa** [aravindballa/gatsby-theme-andy#7]
This theme consists of only the stacking behaviour and few basic styles (like the width of the note and popup element). They don't look great anyway and for people who use this theme, they have to write custom styles in order to get a good looking output.

https://github.com/aravindballa/notes.aravindballa.com/ heavily uses this theme and the components are styled in a way to look like Andy's notes using `tailwindcss`. And the implementations of this theme that I got to see are like that.

I feel this theme should have all those styles by default. So using this theme would be as simple as adding it to `gatsby-config` and writing markdown files in `./content`. Also, I've been thinking of using `theme-ui` as it seems to be a standard to style/theme projects in React. Which means, having custom colors and fonts will be a breeze for the users of this theme.

If you are using this theme and think the above change will break your implementation, feel free to comment, let's discuss.

**Comment by thisizkp** [comment]
I don't think it'll break any. As most of them are copying the components from the notes repository. 

But I do think it'll be easier if we can do this in phases. Like first introduce all the components as-is from the notes (copy, paste). Then introduce theme-UI and make it easier to modify themes in the future.

**Comment by thisizkp** [comment]
I'm planning to convert the theme to use Chakra instead as I'm more comfortable with that. Maybe that could be a separate fork of this or in a separate branch so that it's available for everyone too.

Haven't started any work on it yet, will let you know :)

**Comment by DonaldBough** [comment]
First off thanks for creating this issue. I'm wanting to be more hands off and take the use persona of just forking the repo, adding my name to the site meta data, and instantly start adding notes to /content. So that aspect agrees with how I intend to use this. For now I've forked notes.aravindballa.com and used it. 

The stacking UI looks great. The most noticeable areas of improvement would be using a white pop over bubble, preferably with the pointer at the button, to look more like Andy's. Another would be using light grey footers instead of the current blue. 

Thanks for your time on this!
